### ISSUE TITLE
Dynamic Targetting of pool difficulty for Eloipool

### ISSUE THREAD

**Issue by jeong760** [luke-jr/eloipool#7]
Dears,

Eloipool has an issue with set Dynamic target difficult on the pool because it always set diff as 1. so there are many accpeted and then finally pool goes to no response. 

So is there any method set difficult as current one using Dynamic target option?

My config file setting is 

```
 # Name of the server 
    ServerName = 'Private Eloipool' 

 ### Settings relating to server scaling/load 
 # Share hashes must be below this to be valid shares 
 # If dynamic targetting is enabled, this is a minimum 
    ShareTarget = 0x000000000fffffffffffffffffffffffffffffffffffffffffffffffffffffff 

 # Automatically adjust targets per username  
 #0 = disabled 
 #1 = arbitrary targets 
 #2 = power of two difficulties (zero bit counts) 

  DynamicTargetting = 2

# How many shares per minute to try to achieve on average 
  DynamicTargetGoal = 8 

# DynamicTargetServerAddresses
   DynamicTargetServerAddresses = (::ffff:192.168.10, 3333),

# Number of seconds hashrate is measured over 
  DynamicTargetWindow = 120 

# Should we try to adjust the target quickly when there are a lot of shares? 
  DynamicTargetQuick = True 
```

Regards,
John Ahn

**Comment by luke-jr** [comment]
Remove DynamicTargetServerAddresses

**Comment by jeong760** [comment]
Does it caused of set diificulty as 1?  And What is optimal target hexadecimal values for configuration file?

**Comment by jeong760** [comment]
When DynamicTargetServerAddresses is used?

**Comment by luke-jr** [comment]
DynamicTargetServerAddresses is used when there is an independent server managing the dynamic targeting.

**Comment by jeong760** [comment]
Dears,

Personally I have a few question about Eloipool server configuration.
- How I configured a Dynamic Target server for eloipool?
- Does it support a API for web front end? if not, how I can check for each mining status?
- Does it support a share logging to SQL?

Regards,
John Ahn 
-----Original Message-----
