### ISSUE TITLE
Increasing the rate of mining

### ISSUE THREAD

**Issue by ismaelbej** [luke-jr/eloipool#8]
I'm testing to increase the rate of mining. I run bitcoind in regtest mode (v0.12.0). And adjusted config.py to have a target for a difficult of 0.01, and modified checkShare in eloipool.py to acept all blocks sent by miners. Cpuminer (v2.4.3), with this configuration, mines a block in an average of 400 miliseconds.

The first block is accepted by bitcoind, the rest are being rejected with "bad-cb-amount" or "bad-prevblk". After running like this for 10 minutes, no other block was accepted. After restarting eloipool, the first block mined is accepted, and again the rest are being rejected.

**Comment by luke-jr** [comment]
Don't do that. Regtest isn't meant for mining - use testnet.

**Comment by ismaelbej** [comment]
My problem is not the mining, or regtest, is that eloipool is not able to keep up with a faster pace. When tests are configured to have 1 block/minute it works without problem. But increasing the rate show the problems mentioned.

**Comment by luke-jr** [comment]
Not a problem, because blocks are only 10 minutes on average.
